name: bibtopdf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - transformers
      - torch
      - accelerate
      - requests
      - pandas
      - altair

